export type ProjectTier = | 'hero' | 'featured' | 'standard' | 'minor';
export type ProjectCategory = | 'banking' | 'telecom' | 'government' | 'ai' | 'enterprise' | 'personal';

export type ProjectComplexity = | 'high' | 'medium' | 'low';

export type ProjectRole = | 'frontend' | 'backend' | 'fullstack' | 'architecture';

export interface Project {
  id: string;
  title: string;
  desc: string;
  impact?: string;
  context?: string;
  stack: string;
  tags: string[];
  tier: ProjectTier;
  category: ProjectCategory;
  complexity: ProjectComplexity;
  role: ProjectRole;
  size: 'featured' | 'regular' | 'half';
  featuredOrder?: number;
  year: number;
  duration: string;
  highlightMetrics?: string[];
  companyLogo?: string;
  companyName?: string;
  clientLogo?: string;
  clientName?: string;
  url?: string;
  architectureFlow?: ArchitectureNode[];
}

export interface ArchitectureNode {

  title: string;

  type:
    | 'frontend'
    | 'backend'
    | 'database'
    | 'queue'
    | 'security'
    | 'ai'
    | 'cloud'
    | 'integration'
    | 'gateway'
    | 'testing';

}

export interface ProjectFilterState {
  search: string;
  tags: string[];
  stacks: string[];
  years: number[];
}

export const PROJECTS: Project[] = [

  {
    id: '1',
    title: 'SMS-CONSUMER – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'Optimización de servicio batch para consumo de colas AS400 e integración con Kafka.',
    impact: 'Optimización de procesamiento batch mediante paralelización de consumo AS400 y modernización backend sobre Java 25.',
    stack: 'Spring Boot',
    tags: ['AS400', 'Kafka', 'Redis', 'SonarQube', 'CI/CD', 'Jenkins', 'ArgoCD', 'Hexagonal Architecture'],
    tier: 'hero',
    category: 'banking',
    complexity: 'high',
    role: 'backend',
    featuredOrder: 1,
    size: 'featured',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['Kafka', 'AS400', 'Java 25', 'Hexagonal Architecture'],
    architectureFlow: [
      {title: 'AS400', type: 'integration'},
      {title: 'Kafka', type: 'queue'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'Redis', type: 'database'}
    ],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '2',
    title: 'Validation-Listener – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'Listener backend para procesamiento de colas AS400 e integración distribuida.',
    impact: 'Reducción de tiempos de respuesta mediante consumo eficiente de colas AS400 e integración con Redis y Kafka.',
    stack: 'Spring Boot',
    tags: ['AS400', 'Redis', 'Kafka', 'CI/CD', 'Jenkins', 'ArgoCD'],
    tier: 'hero',
    category: 'banking',
    complexity: 'high',
    role: 'backend',
    featuredOrder: 2,
    size: 'featured',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['Redis', 'Kafka', 'AS400', 'Distributed Cache'],
    architectureFlow: [
      {title: 'AS400', type: 'integration'},
      {title: 'Kafka', type: 'queue'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'Redis', type: 'database'}
    ],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '3',
    title: 'SIGED – RENIEC',
    context: 'CloudComputing Perú S.A.C. · RENIEC · 2023',
    desc: 'Sistema de gestión documental para procesos institucionales.',
    impact: 'Modernización tecnológica y optimización de procesos documentales institucionales.',
    stack: 'Angular · React · Spring Boot',
    tags: ['Angular Material', 'PL/SQL', 'Spring Boot', 'Jenkins', 'SonarQube'],
    tier: 'hero',
    category: 'government',
    complexity: 'high',
    role: 'fullstack',
    featuredOrder: 3,
    size: 'featured',
    year: 2023,
    duration: '8 Meses',
    highlightMetrics: ['Spring Boot', 'Angular', 'React', 'Government System'],
    architectureFlow: [
      {title: 'Angular', type: 'frontend'},
      {title: 'React', type: 'frontend'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'PL/SQL', type: 'database'}
    ],
    companyLogo: '/imagen/LOGO_CC.svg',
    companyName: 'CloudComputing Perú S.A.C.',
    clientLogo: '/imagen/LOGO_RENIEC.svg',
    clientName: 'RENIEC',
  },

  {
    id: '4',
    title: 'Botón de Pago – CLARO',
    context: 'INDRA PERÚ · CLARO · 2025',
    desc: 'Plataforma de integración y procesamiento de pagos.',
    impact: 'Incremento de confiabilidad y seguridad en flujos de pagos digitales empresariales.',
    stack: 'Angular · Spring Boot',
    tags: ['OWASP ZAP', 'Mockito', 'Jest', 'SonarQube', 'CI/CD'],
    tier: 'hero',
    category: 'telecom',
    complexity: 'high',
    role: 'fullstack',
    featuredOrder: 4,
    size: 'featured',
    year: 2025,
    duration: '12 Meses',
    highlightMetrics: ['OWASP', 'Payments', 'Spring Boot', 'Enterprise Security'],
    architectureFlow: [
      {title: 'Angular', type: 'frontend'},
      {title: 'BFF', type: 'gateway'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'OWASP', type: 'security'}
    ],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_CLARO.svg',
    clientName: 'CLARO',
  },

  {
    id: '5',
    title: 'Sistema de Lenguaje de Señas - UA',
    context: 'TESIS · 2025',
    desc: 'Sistema inteligente de reconocimiento de señas en tiempo real.',
    impact: 'Implementación funcional de reconocimiento gestual mediante IA y visión computacional.',
    stack: 'Angular · Flask · Node.js',
    tags: ['TensorFlow', 'Keras', 'MediaPipe', 'OpenCV', 'MongoDB Atlas'],
    tier: 'hero',
    category: 'ai',
    complexity: 'high',
    role: 'fullstack',
    featuredOrder: 5,
    size: 'featured',
    year: 2025,
    duration: '6 Meses',
    highlightMetrics: ['TensorFlow', 'OpenCV', 'MediaPipe', 'Real-Time AI'],
    architectureFlow: [
      {title: 'Camera', type: 'integration'},
      {title: 'MediaPipe', type: 'ai'},
      {title: 'TensorFlow', type: 'ai'},
      {title: 'Flask API', type: 'backend'}
    ],
    companyLogo: '/imagen/LOGO_UA.svg',
    companyName: 'Universidad Autónoma del Perú',
    clientLogo: '/imagen/FOTO.svg',
    clientName: 'Diego Gonzalez',
  },

  {
    id: '6',
    title: 'GESINTEL – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'Sistema de validación de personas PEP y entidades financieras.',
    impact: 'Fortalecimiento de validaciones financieras y actualización tecnológica del sistema.',
    stack: 'React · Spring Boot',
    tags: ['SonarQube', 'CI/CD', 'Jenkins', 'Postman'],
    tier: 'featured',
    category: 'banking',
    complexity: 'medium',
    role: 'fullstack',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['PEP Validation', 'Spring Boot', 'React'],
    architectureFlow: [
      {title: 'React', type: 'frontend'},
      {title: 'Validation Engine', type: 'backend'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'Database', type: 'database'}
    ],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '7',
    title: 'BFF – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'Backend for Frontend para orquestación de servicios empresariales.',
    impact: 'Optimización de consumo de APIs y desacoplamiento de servicios backend.',
    stack: 'Spring Boot',
    tags: ['Hexagonal Architecture', 'CI/CD', 'Jenkins'],
    tier: 'featured',
    category: 'banking',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['BFF', 'API Gateway', 'Hexagonal Architecture'],
    architectureFlow: [
      {title: 'Frontend Apps', type: 'frontend'},
      {title: 'BFF', type: 'gateway'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'Microservices', type: 'integration'}
    ],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '8',
    title: 'Validation-API – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'API empresarial para validación de personas PEP.',
    impact: 'Mejora de rendimiento y estabilidad mediante optimización de validaciones backend.',
    stack: 'Spring Boot',
    tags: ['SonarQube', 'CI/CD', 'Jenkins'],
    tier: 'featured',
    category: 'banking',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['REST API', 'Validation Services', 'Spring Boot'],
    architectureFlow: [
      {title: 'Clients', type: 'frontend'},
      {title: 'REST API', type: 'gateway'},
      {title: 'Spring Boot', type: 'backend'},
      {title: 'Validation Engine', type: 'integration'}
    ],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '9',
    title: 'Expediente Virtual – INTEGRATEL',
    context: 'INDRA PERÚ · INTEGRATEL · 2024',
    desc: 'Desarrollo de módulos para sistema de expedientes digitales.',
    impact: 'Reducción de incidencias y mejora de estabilidad en producción.',
    stack: 'Angular',
    tags: ['Azure AD B2C', 'Jasmine', 'Karma', 'SonarQube'],
    tier: 'featured',
    category: 'telecom',
    complexity: 'medium',
    role: 'frontend',
    size: 'half',
    year: 2024,
    duration: '4 Meses',
    highlightMetrics: ['Angular', 'Azure AD', 'Testing'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '10',
    title: 'PACIFYC – INTEGRATEL',
    context: 'INDRA PERÚ · INTEGRATEL · 2024',
    desc: 'Plataforma de gestión interna empresarial.',
    impact: 'Migración y optimización de procesos internos empresariales.',
    stack: 'Angular · Spring Boot',
    tags: ['PL/SQL', 'Mockito', 'SonarQube'],
    tier: 'featured',
    category: 'enterprise',
    complexity: 'medium',
    role: 'fullstack',
    size: 'regular',
    year: 2024,
    duration: '8 Meses',
    highlightMetrics: ['Enterprise Platform', 'PL/SQL', 'Spring Boot'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '11',
    title: 'SISTEC – INTEGRATEL',
    context: 'INDRA PERÚ · INTEGRATEL · 2025',
    desc: 'Sistema interno empresarial para optimización operativa.',
    impact: 'Mejora de procesos internos y mantenimiento evolutivo.',
    stack: 'Angular · Spring Boot',
    tags: ['Oracle', 'PL/SQL', 'Mockito'],
    tier: 'featured',
    category: 'enterprise',
    complexity: 'medium',
    role: 'fullstack',
    size: 'regular',
    year: 2025,
    duration: '10 Meses',
    highlightMetrics: ['Oracle', 'Enterprise', 'Spring Boot'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '12',
    title: 'WEB INCIDENTES – CLARO',
    context: 'INDRA PERÚ · CLARO · 2025',
    desc: 'Sistema web para gestión de incidentes operativos.',
    impact: 'Modernización tecnológica y optimización del flujo de incidencias.',
    stack: 'Angular · Spring Boot',
    tags: ['BFF', 'OWASP ZAP', 'Jest'],
    tier: 'featured',
    category: 'telecom',
    complexity: 'medium',
    role: 'fullstack',
    size: 'half',
    year: 2025,
    duration: '8 Meses',
    highlightMetrics: ['Incident Management', 'OWASP', 'BFF'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_CLARO.svg',
    clientName: 'CLARO',
  },

  {
    id: '13',
    title: 'Jerarquía de Ventas – INTEGRATEL',
    context: 'INDRA PERÚ · INTEGRATEL · 2025',
    desc: 'Sistema para gestión jerárquica de ventas.',
    impact: 'Optimización de procesos comerciales y jerarquización empresarial.',
    stack: 'Angular · React · Spring Boot',
    tags: ['Oracle', 'Jasmine', 'Karma'],
    tier: 'featured',
    category: 'telecom',
    complexity: 'medium',
    role: 'fullstack',
    size: 'half',
    year: 2025,
    duration: '8 Meses',
    highlightMetrics: ['Sales Hierarchy', 'Angular', 'React'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '14',
    title: 'Expediente Virtual – Bandeja SAR',
    context: 'INDRA PERÚ · INTEGRATEL · 2024',
    desc: 'Módulo de bandeja SAR para gestión documental.',
    impact: 'Optimización del flujo documental empresarial.',
    stack: 'Angular · Spring Boot',
    tags: ['Mockito', 'Figma', 'Karma'],
    tier: 'standard',
    category: 'enterprise',
    complexity: 'low',
    role: 'fullstack',
    size: 'regular',
    year: 2024,
    duration: '4 Meses',
    highlightMetrics: ['SAR', 'Angular', 'Spring Boot'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '15',
    title: 'SIVADAC – INTEGRATEL',
    context: 'INDRA PERÚ · INTEGRATEL · 2024',
    desc: 'Sistema de validación documental.',
    impact: 'Reducción de errores operativos en validaciones documentales.',
    stack: 'Angular',
    tags: ['Figma', 'Karma', 'SonarQube'],
    tier: 'standard',
    category: 'enterprise',
    complexity: 'low',
    role: 'frontend',
    size: 'regular',
    year: 2024,
    duration: '8 Meses',
    highlightMetrics: ['Document Validation', 'Angular'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_INTEGRATEL.svg',
    clientName: 'INTEGRATEL',
  },

  {
    id: '16',
    title: 'PCD – CLARO',
    context: 'INDRA PERÚ · CLARO · 2025',
    desc: 'Sistema de control documental empresarial.',
    impact: 'Mejora de trazabilidad y control de flujos documentales.',
    stack: 'Angular · Spring Boot',
    tags: ['BFF', 'Jest', 'OWASP ZAP'],
    tier: 'standard',
    category: 'telecom',
    complexity: 'medium',
    role: 'fullstack',
    size: 'half',
    year: 2025,
    duration: '8 Meses',
    highlightMetrics: ['Document Control', 'BFF'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_CLARO.svg',
    clientName: 'CLARO',
  },

  {
    id: '17',
    title: 'Mesa de Partes Virtual – RENIEC',
    context: 'CloudComputing Perú S.A.C. · RENIEC · 2023',
    desc: 'Sistema virtual para recepción y gestión documental.',
    impact: 'Digitalización de procesos documentales institucionales.',
    stack: 'Angular · React · Spring Boot',
    tags: ['Bootstrap', 'Spring Boot'],
    tier: 'standard',
    category: 'government',
    complexity: 'medium',
    role: 'fullstack',
    size: 'regular',
    year: 2023,
    duration: '7 Meses',
    highlightMetrics: ['Digital Process', 'Government'],
    companyLogo: '/imagen/LOGO_CC.svg',
    companyName: 'CloudComputing Perú S.A.C.',
    clientLogo: '/imagen/LOGO_RENIEC.svg',
    clientName: 'RENIEC',
  },

  {
    id: '18',
    title: 'Módulo Usuario Final – RENIEC',
    context: 'CloudComputing Perú S.A.C. · RENIEC · 2023',
    desc: 'Módulo de experiencia y gestión de usuarios.',
    impact: 'Mejora de experiencia de usuario y accesibilidad del sistema.',
    stack: 'Angular · React · Spring Boot',
    tags: ['Mockito', 'PL/SQL'],
    tier: 'standard',
    category: 'government',
    complexity: 'medium',
    role: 'fullstack',
    size: 'regular',
    year: 2023,
    duration: '8 Meses',
    highlightMetrics: ['UX Improvement', 'Government'],
    companyLogo: '/imagen/LOGO_CC.svg',
    companyName: 'CloudComputing Perú S.A.C.',
    clientLogo: '/imagen/LOGO_RENIEC.svg',
    clientName: 'RENIEC',
  },

  {
    id: '19',
    title: 'Migración SIGED a JBoss – RENIEC',
    context: 'CloudComputing Perú S.A.C. · RENIEC · 2023',
    desc: 'Migración tecnológica del sistema SIGED hacia JBoss.',
    impact: 'Incremento de estabilidad y modernización de infraestructura.',
    stack: 'Angular · React · Spring Boot',
    tags: ['JBoss', 'Jenkins', 'CI/CD'],
    tier: 'standard',
    category: 'government',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2023,
    duration: '8 Meses',
    highlightMetrics: ['JBoss', 'Migration', 'Infrastructure'],
    companyLogo: '/imagen/LOGO_CC.svg',
    companyName: 'CloudComputing Perú S.A.C.',
    clientLogo: '/imagen/LOGO_RENIEC.svg',
    clientName: 'RENIEC',
  },

  {
    id: '20',
    title: 'MAIL-CONSUMER – Scotiabank',
    context: 'IDM Technology · Scotiabank · 2026',
    desc: 'Servicio batch para consumo de colas AS400.',
    impact: 'Optimización de procesamiento de colas y servicios backend.',
    stack: 'Spring Boot',
    tags: ['Kafka', 'AS400', 'CI/CD'],
    tier: 'minor',
    category: 'banking',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['Kafka', 'AS400'],
    companyLogo: '/imagen/LOGO_IDM.svg',
    companyName: 'IDM Technology',
    clientLogo: '/imagen/LOGO_SB.svg',
    clientName: 'Scotiabank',
  },

  {
    id: '21',
    title: 'Botón de Pago (BFF) – CLARO',
    context: 'INDRA PERÚ · CLARO · 2026',
    desc: 'BFF para orquestación de servicios de pagos.',
    impact: 'Mejora de seguridad y consumo de APIs empresariales.',
    stack: 'Node.js',
    tags: ['Testing', 'SonarQube'],
    tier: 'minor',
    category: 'telecom',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['BFF', 'Node.js'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_CLARO.svg',
    clientName: 'CLARO',
  },

  {
    id: '22',
    title: 'WEB INCIDENTES (BFF) – CLARO',
    context: 'INDRA PERÚ · CLARO · 2026',
    desc: 'BFF para integración de servicios empresariales.',
    impact: 'Optimización de comunicación entre frontend y backend.',
    stack: 'Node.js',
    tags: ['Testing', 'CI/CD'],
    tier: 'minor',
    category: 'telecom',
    complexity: 'medium',
    role: 'backend',
    size: 'half',
    year: 2026,
    duration: '4 Meses',
    highlightMetrics: ['BFF', 'Node.js'],
    companyLogo: '/imagen/LOGO_INDRA.svg',
    companyName: 'INDRA PERÚ',
    clientLogo: '/imagen/LOGO_CLARO.svg',
    clientName: 'CLARO',
  },

  {
    id: '23',
    title: 'Gestión de Apuestas Deportivas - PERSONAL',
    context: 'PROYECTO PERSONAL · 2025',
    desc: 'Sistema de gestión y centralización de apuestas deportivas.',
    impact: 'Centralización y automatización de apuestas deportivas.',
    stack: 'Angular · Node.js',
    tags: ['MongoDB Atlas', 'Jasmine', 'Karma'],
    tier: 'minor',
    category: 'personal',
    complexity: 'medium',
    role: 'fullstack',
    size: 'half',
    year: 2025,
    duration: '4 Meses',
    highlightMetrics: ['MongoDB', 'Node.js'],
    companyLogo: '/imagen/FOTO.svg',
    companyName: 'Diego Gonzalez',
  },

  {
    id: '24',
    title: 'Detección de Mascarilla (Expotec 2021) - UA',
    context: 'Universidad Autónoma del Perú · 2021',
    desc: 'Sistema de visión computacional para detección de mascarillas.',
    impact: 'Proyecto ganador en Expotec 2021 mediante IA y visión computacional.',
    stack: 'Python · Flask · Angular',
    tags: ['TensorFlow', 'OpenCV', 'Keras'],
    tier: 'minor',
    category: 'ai',
    complexity: 'low',
    role: 'fullstack',
    size: 'half',
    year: 2021,
    duration: '4 Meses',
    highlightMetrics: ['Computer Vision', 'TensorFlow'],
    companyLogo: '/imagen/LOGO_UA.svg',
    companyName: 'Universidad Autónoma del Perú',
    clientLogo: '/imagen/FOTO.svg',
    clientName: 'Diego Gonzalez',
  }

];
